import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useRef, useState } from "react"
import CLOUDS from "vanta/dist/vanta.clouds.min"
import * as THREE from "three"

export default function Home() {
    const [vantaEffect, setVantaEffect] = useState(0)
    const vantaRef = useRef(null)

    useEffect(() => {
        if (!vantaEffect) {
            setVantaEffect(
                CLOUDS({
                    el: "#vanta",
                    THREE,
                    mouseControls: true,
                    touchControls: true,
                    gyroControls: false,
                    minHeight: 200.00,
                    minWidth: 200.00,
                    sunGlareColor: 0xd44009,
                    speed: 1.30
                })
            );
        }
        return () => {
            if (vantaEffect) {
                vantaEffect.destory()
            }
        }
    }, [vantaEffect])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div id="vanta" className='border p-20 ml-50'>
                JIALIN VANTA DEMO
            </div>
        </div>
    )
}
